# Generated by Django 5.1.4 on 2025-03-19 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('tech', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('photo', models.FileField(upload_to='')),
                ('date', models.DateField(default=datetime.date(2025, 3, 19))),
            ],
            options={
                'db_table': 'profileinfo',
            },
        ),
    ]
